### PR TITLE
On click toggle

### PR DESCRIPTION
**Pull request by goodmorninggoaway**
Use Case: clicking a toggle icon to view child nodes does not equal selecting that node.
Add onClickIcon to handle this case.

### CODE REVIEW

**Comment by witalobenicio** [comment]
How can we use that? I tried to pass an onClickIcon prop to TreeBeard component but it didn't work.

**Comment by goodmorninggoaway** [comment]
I didn't update the default decorators to use this. You have to use it in a custom decorator.

Example: 
```
const PoolContainer = ({ onClick, onClickIcon, node }) => {
    const hasChildren = node.children && node.children.length;

    return (
        <div className={cx('node')}>
            <Caret
                onClick={hasChildren ? onClickIcon : null}
                toggled={node.toggled}
                className={cx('caret', { invisible: !hasChildren })}
            />
            <PoolNodeIcon onClick={onClick} />
            <PoolNodeHeader node={node} onClick={onClick} />
        </div>
    );
};

```

I'm using this in a dropdown, and I want it to auto-close when i select a node, but not when I click the caret to explode the tree node.

**Comment by witalobenicio** [comment]
I'm using like this:
```
<Treebeard
                                                    onClickIcon={this.onClickIcon.bind(this)}
                                                    data={this.state.dataSecondarySubject}
                                                    style={treeStyle}
                                                    onToggle={this.onToggleSecondary.bind(this)}
                                                />
```

**Comment by goodmorninggoaway** [comment]
If you have no custom decorators, nothing is using it. I didn't want to
break existing functionality.

**Comment by armel22** [comment]
can someone merge this PR? 
Please !

**Comment by kazazor** [comment]
@goodmorninggoaway - why not change the default decorators? This is just adding functionality isn't it How will it break the existing one?

I would also expect a change in the README file saying you can pass this new prop..

**Comment by mpeula-pe** [comment]
can someone merge this PR?
It would be a very nice feature!

**Comment by MichaelDeBoey** [comment]
@mpeula-pe: @goodmorninggoaway First needs to resolve the conflicts before this one can be merged

**Comment by Lukejkw** [comment]
When will this be merged in and available?

**Comment by mjw56** [comment]
This looks good to add? I also have a use case in a real world app for this functionality. Cheers!

**Comment by buptlee** [comment]
When will this be merged in and available?

**Pull request closed without merging**
